### ISSUE TITLE
Alle drei Suchen zeigen irgendwie keine Pixel in der Vorschau

### ISSUE THREAD

**Issue by TrandyAndy** [TrandyAndy/Bad-Pixel#20]
Sagt Julian

**Comment by TrandyAndy** [comment]
27.02. alle Farben waren gleichzietig zu sehehn.
Blau überdeck aber fast immer rot.

Kann nicht rekonstruioert werden

**Comment by JLS666** [comment]
Auf dem Mac immer noch so:

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/43670180/109620166-dc0b1c00-7b39-11eb-8c30-0fca79e2ac12.png">

Hier vergleich mit Moving Window alleine aktiviert:
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/43670180/109620416-255b6b80-7b3a-11eb-99c7-317a4182711a.png">

**Comment by JLS666** [comment]
Positives Beispiel

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/43670180/109723805-e3204180-7bae-11eb-816b-156b7451fd80.png">
