### ISSUE TITLE
EXE unter Windows Probleme

### ISSUE THREAD

**Issue by JLS666** [TrandyAndy/Bad-Pixel#31]
Bugs:
- Das Vorschaubild öffnet sich nicht.
- Okay Button wird nicht freigeschaltet. 
- Keine Textausgabe (außer bei Rohbilder speichern)
- Korrigierte Bilder werden nicht gespeichert

<img width="466" alt="image" src="https://user-images.githubusercontent.com/43670180/109414676-6a559580-79b4-11eb-8d0d-a14f6e19d728.png">

<img width="466" alt="image" src="https://user-images.githubusercontent.com/43670180/109414788-0e3f4100-79b5-11eb-9fa7-1840a5f238c0.png">

**Comment by TrandyAndy** [comment]
was ist an der Rohbild ausgabe anders?

**Comment by JLS666** [comment]
Siehe oben:

"Keine Textausgabe (außer bei Rohbilder speichern)"

**Comment by JLS666** [comment]
Gelöst, Problem war opencv-pyhton-headless kannte die killAllWindows Funktion nicht. Installation von opencv-python löste das Problem
