### ISSUE TITLE
Bug, wenn man zwei Sensoren mit dem selben Namen erstellen will...

### ISSUE THREAD

**Issue by JLS666** [TrandyAndy/Bad-Pixel#32]
Bug, wenn man zwei Sensoren mit dem selben Namen erstellen will, tauchen beide in der Liste auf.

**Comment by JLS666** [comment]
Vielleicht alle BPM eines gelöschten Sensors löschen?? 
Weil wenn ich den Sensor gleich nenne, kennt er schon die BPM.

**Comment by TrandyAndy** [comment]
es gibt jetzt keine 2 gleichen mehr.
aber wenn er zuerst gelöscht wurde geht das schon
